version: "3.6"

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
      
  # envoy:
  #   build: ./envoy
  #   image: envoy
    
  # frontend:
  #   build: ./frontend
  #   image: frontend
  #   ports:
  #     - 80:80
      
  backend:
    build: ./backend/app/
    image: backend:master
    ports:
      - 80:3000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    # links:
    #   - mongo
    # depends_on: 
    #   - mongo
    
  process_cli:
    image: gcr.io/cyntegrity/processcli:master
    # links:
    #   - mongo
    # depends_on: 
    #   - mongo